apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: jenkins-casc
              mountPath: /var/jenkins_home/jenkins-casc.yaml
              subPath: jenkins-casc.yaml
          env:
            - name: JAVA_OPTS
              value: "-Djenkins.install.runSetupWizard=false -Djenkins.CascConfigurationLocation=/var/jenkins_home/jenkins-casc.yaml"
      volumes:
        - name: jenkins-home
          hostPath:
            path: /Users/tal_halias/Desktop/jenkins_home
        - name: jenkins-casc
          configMap:
            name: jenkins-casc
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: jenkins
