# Use the official Python image
FROM python:3.12

# Set the working directory
WORKDIR /usr/src/app

# Copy the requirements file
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY /app .

# Copy the test file
COPY test_main.py .

# Expose the port the app runs on
EXPOSE 8081

# Run the tests
CMD ["pytest", "test_main.py"]
