version: '3.8'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongoDB
    ports:
      - 27017:27017
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://root:mongoDB@mongodb:27017/weather_db?authSource=admin
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    networks:
      - app-network

  test-app:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - MONGO_URL=mongodb://root:mongoDB@mongodb:27017/weather_db?authSource=admin
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
