# Use the official Python image
FROM python:3.12

# Set the working directory
WORKDIR /usr/src/app

# Copy the requirements file
COPY requirements.txt .


RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY app .

# Copy the test file
COPY test_main.py .

# Expose the port (if needed, but typically not necessary for testing)
EXPOSE 8081

# Command to run the tests
CMD ["pytest", "test_main.py"]
