apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent-pod
spec:
  containers:
    - name: dind
      image: drpsychick/dind-buildx-helm
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
