apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "weather-app.fullname" . }}
  labels:
    app: {{ include "weather-app.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "weather-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "weather-app.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: tal5041996/weather-app:latest  
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: MONGO_DB_HOST
              value: "{{ .Values.mongo.host }}"
            - name: MONGO_DB_PORT
              value: "{{ .Values.mongo.port }}"
            - name: MONGO_DB_NAME
              value: "{{ .Values.mongo.database }}"
            - name: MONGO_DB_USER
              value: "{{ .Values.mongo.username }}"
            - name: MONGO_DB_PASS
              value: "{{ .Values.mongo.password }}"
