apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-casc
  namespace: default
data:
  jenkins-casc.yaml: | 
    jenkins:
      securityRealm:
        local:
          allowsSignup: false
          users:
            - id: admin
              password: ${JENKINS_PASSWORD}
      authorizationStrategy:
        loggedInUsersCanDoAnything:
          allowAnonymousRead: false
      unclassified:
        location:
          url: http://localhost:30000/
      tool:
        git:
          installations:
            - home: "git"
      plugins:
        required:
          - kubernetes:3937.vd7b_82db_e347b_
          - workflow-aggregator:596.v8c21c963d92d
          - git:5.2.0
          - configuration-as-code:1647.ve39ca_b_829b_42
          - gitlab-plugin:1.7.14
          - blueocean:1.27.4
          - workflow-multibranch:756.v891d88f2cd46
          - login-theme:46.v36f624efb_23d
          - prometheus:2.2.3
          - github-oauth:588.vf696a_350572a_
