apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'weather-app'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - default
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app]
            action: keep
            regex: weather-app
          - source_labels: [__address__, __meta_kubernetes_endpoint_port_name]
            action: replace
            target_label: __address__
            regex: (.+):(\d+);(\d+)
            replacement: $1:$2
        scheme: http
        static_configs:
          - targets: ['10.99.87.208:32098']  # Adjust with your service DNS and port
            labels:
              app: 'weather-app'





