pipeline {
    agent {
        kubernetes {
            label 'jenkins-agent'
            yamlFile 'application/jenkins-agent.yaml'
            defaultContainer 'dind'
        }
    }

    environment {
        DOCKER_IMAGE = 'tal5041996/weather-app'
        DOCKERHUB_CREDENTIALS = 'docker-cred'
        GITHUB_CREDENTIALS = 'github-token'
        DOCKER_TAG = 'latest'
        FEATURE_BRANCH = 'feature'
        REPO_URL = 'https://github.com/Talh12/finalProject.git'
        APPLICATION_DIR = 'application'
        VERSION = "${env.BUILD_NUMBER}"
    }

    stages {
        stage("Checkout code") {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${DOCKER_IMAGE}:${VERSION}", "-f ${APPLICATION_DIR}/Dockerfile ${APPLICATION_DIR}")
                }
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS) {
                        docker.image("${DOCKER_IMAGE}:${VERSION}").push()
                    }
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    sh "docker-compose -f ${APPLICATION_DIR}/docker-compose.yaml up --build --abort-on-container-exit"
                }
            }
        }

        stage('Debug Working Directory') {
            steps {
                script {
                    sh 'pwd'
                    sh 'ls -la'
                }
            }
        }

        stage('Check and Push Changes to Feature Branch') {
            steps {
                script {
                    // Configure Git settings
                    sh 'git config --global --add safe.directory /home/jenkins/agent/workspace/weather-app'
                    sh 'git config --global user.email "halias32236@gmail.com"'
                    sh 'git config --global user.name "Talh12"'

                    // Fetch latest changes from the remote repository
                    sh 'git fetch origin "+refs/heads/*:refs/remotes/origin/*"'

                    // Checkout the feature branch
                    sh "git checkout --track origin/${FEATURE_BRANCH}"

                    // Add all changes (including deleted files)
                    sh 'git add -A'

                    // Check if there are changes to commit
                    def gitStatus = sh(script: 'git status --porcelain', returnStdout: true).trim()

                    if (gitStatus != "") {
                        // Commit changes
                        sh 'git commit -m "Automated commit by Jenkins"'

                        // Push changes to the feature branch
                        sh "git push origin ${FEATURE_BRANCH}"
                    } else {
                        echo 'No changes to commit.'
                    }
                }
            }
        }
    }

    post {
        always {
            script {
                currentBuild.result = 'SUCCESS'
            }
        }
    }
}
