name: CI Pipeline

on:
  push:
    branches:
      - feature

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          clean: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./application
          file: ./application/Dockerfile
          push: true
          tags: tal5041996/weather-app:latest

      - name: Test with Docker Compose
        run: |
          docker-compose -f ./application/docker-compose.yaml up --abort-on-container-exit --exit-code-from app

      - name: Configure Git
        run: |
          git config --global user.email "halias32236@gmail.com"
          git config --global user.name "Talh12"

      - name: Commit and Push changes to GitHub
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT_GITHUB }}@github.com/${{ github.repository }}.git
          git fetch origin
          git add .
          git diff-index --quiet HEAD || git commit -m "Automated commit by GitHub Actions"
          git push origin feature
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}

      - name: Merge feature into main
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT_GITHUB }}@github.com/${{ github.repository }}.git
          git checkout main
          git pull origin main
          git merge feature
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
